package org.omg.IOP;


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/ec2-user/workspace/Corretto8/macos/x64/build/Corretto8Src/installers/mac/tar/corretto-build/buildRoot/src/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, October 14, 2021 9:08:58 PM GMT
*/

public interface TAG_POLICIES
{

  /**
       * A profile component containing the sequence of QoS policies exported
       * with the object reference by an object adapter.
       */
  public static final int value = (int)(2L);
}
